backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow

media_folder: "public/assets"

public_folder: "/assets"

collections:
  - name: "blog"

    label: "Blog"

    folder: "src/posts"

    create: true

    slug: "{{slug}}"

    fields:
      - { label: "Title", name: "title", widget: "string" }

      - { label: "Description", name: "description", widget: "string" }

      - { label: "Date", name: "date", widget: "datetime" }

      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          required: false,
        }

      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }

      - { label: "Body", name: "body", widget: "markdown" }
